"""create longitudinal core

Revision ID: bb442bccae1b
Revises:
Create Date: 2026-10-09 00:26:03.591063

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb442bccae1b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("demographics_json", sa.JSON(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_patients_alias"), ["alias"], unique=False)

    op.create_table(
        "encounters",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_encounters_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_encounters_patient_id"), ["patient_id"], unique=False)

    op.create_table(
        "history_events",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("fact_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("correction_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["history_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_events_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_history_events_encounter_id"), ["encounter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_history_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_history_events_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "questionnaire_responses",
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("encounter_id", sa.String(length=36), nullable=False),
        sa.Column("scale_id", sa.String(length=50), nullable=False),
        sa.Column("item_scores_json", sa.JSON(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("questionnaire_responses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_questionnaire_responses_encounter_id"), ["encounter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_questionnaire_responses_measured_at"), ["measured_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_questionnaire_responses_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_questionnaire_responses_scale_id"), ["scale_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questionnaire_responses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questionnaire_responses_scale_id"))
        batch_op.drop_index(batch_op.f("ix_questionnaire_responses_patient_id"))
        batch_op.drop_index(batch_op.f("ix_questionnaire_responses_measured_at"))
        batch_op.drop_index(batch_op.f("ix_questionnaire_responses_encounter_id"))

    op.drop_table("questionnaire_responses")
    with op.batch_alter_table("history_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_history_events_patient_id"))
        batch_op.drop_index(batch_op.f("ix_history_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_history_events_encounter_id"))
        batch_op.drop_index(batch_op.f("ix_history_events_category"))

    op.drop_table("history_events")
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_encounters_patient_id"))
        batch_op.drop_index(batch_op.f("ix_encounters_occurred_at"))

    op.drop_table("encounters")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_alias"))

    op.drop_table("patients")
    # ### end Alembic commands ###
